# Fly.io 설정 파일
app = "savemetoilet-backend"
primary_region = "nrt" # 도쿄 리전 (한국과 가장 가까움)

[build]
  dockerfile = "Dockerfile"

[env]
  # 환경변수는 Fly.io 대시보드에서 설정
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/v1/test/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256