# SaveMeToilet Backend Configuration

server:
  port: 8080

spring:
  application:
    name: savemetoilet-backend
    
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:savemetoilet
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
      path: /h2-console

# Seoul Open Data API Configuration
seoul:
  api:
    key: ${SEOUL_API_KEY:your_seoul_api_key_here}
    base-url: http://openapi.seoul.go.kr:8088
    toilet-service: SearchPublicToiletPOIService
    timeout: 30s

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173

# Logging Configuration
logging:
  level:
    com.savemetoilet: DEBUG
    org.springframework.web: DEBUG
    root: INFO